---
name: eleventh_hour
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.7
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.0.0
  http: ^0.12.1
  connectivity: ^0.4.9
  image_picker: ^0.6.7+4
  provider: ^4.0.5+1
  flutter_spinkit: ^4.1.2
  page_transition: ^1.1.6
  rflutter_alert: ^1.0.3
  fluttertoast: ^3.1.3
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  google_nav_bar: ^3.0.0
  gooey_carousel: ^0.1.2
  slimy_card: ^1.0.4
  firebase_storage: ^3.1.6
  flutter_inner_drawer: ^0.5.6+1
  cloud_firestore: ^0.13.7
  cached_network_image: ^2.2.0+1
  shimmer: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: EcommerceAppUI
      fonts:
        - asset: assets/fonts/EcommerceAppUI.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Bold.ttf
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-BoldItalic.ttf
        - asset: assets/fonts/Karla-Italic.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
